name: Quality Workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      # - name: Run tests
      #   run: yarn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Check SonarQube Quality Gate
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
      #     PR_ID: ${{ github.event.pull_request.number }}
      #   run: |
      #     echo "Waiting for SonarQube analysis to complete..."
      #     sleep 20
      #     result=$(curl -u "$SONAR_TOKEN": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY&&pullRequest=$PR_ID")
      #     status=$(echo "$result" | jq -r '.projectStatus.status')

      #     echo "SonarQube Quality Gate status: $status"
      #     if [ "$status" != "OK" ]; then
      #         echo "SonarQube Quality Gate failed"
      #         exit 1
      #     else
      #         echo "SonarQube Quality Gate passed"
      #     fi
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}